services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - CUDA_VISIBLE_DEVICES=        # força CPU pq minha placa de vídeo é fraca.
    entrypoint: ["/bin/sh", "-c", "ollama serve & skeep 3 && ollama pull qwen3.5:0.8b && wait"] # Chama o qwen3.5 de 0.8b. 
    restart: unless-stopped

  main-server:
    build: ./main-server
    depends_on:
      - ollama
    environment:
      - OLLAMA_URL=http://ollama:11434

volumes:
  ollama_data:    # persiste os modelos baixados